modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-only"
[[mods]]
modId="radium"
version="0.7.7g"
displayName="Radium"
logoFile="icon.png"
description='''
An unofficial fork of Litihum mod, maked to work on FML.
'''
credits="NanoLive, CaffeineMC"
authors="NanoLive"
